version: '3.9'

services:
  competition:
    build:
      context: ./../../
      dockerfile: docker/dockerfiles/competition/Dockerfile
    env_file: .env
    networks:
      internal:
    depends_on:
      - postgresql

  postgresql:
    image: postgres:17.0
    container_name: postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      internal:

networks:
  internal:
    driver: bridge